version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tcheck_intranet_db
    environment:
      POSTGRES_USER: tcheck_intranet_user
      POSTGRES_PASSWORD: tcheck_intranet_pass26
      POSTGRES_DB: tcheck_intranet
    ports:
      - "5434:5432"
    volumes:
      - tcheck_pgdata:/var/lib/postgresql/data

volumes:
  tcheck_pgdata:
