"""add_shift_type_shift_hours_custom_shift_times

Revision ID: 2147c6a26f2e
Revises: a7c7e2dcb002
Create Date: 2026-07-03 15:24:39.378267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2147c6a26f2e'
down_revision = 'a7c7e2dcb002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_type', sa.String(), server_default='standard', nullable=False))
        batch_op.add_column(sa.Column('shift_hours', sa.String(), server_default='7am-5pm', nullable=False))
        batch_op.add_column(sa.Column('custom_shift_start', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('custom_shift_end', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('custom_shift_end')
        batch_op.drop_column('custom_shift_start')
        batch_op.drop_column('shift_hours')
        batch_op.drop_column('shift_type')

    # ### end Alembic commands ###
