"""add ble_beacon and beacon_assignment

Revision ID: 2e9345d2b883
Revises: e488a1f408e3
Create Date: 2026-07-14 23:12:54.533079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9345d2b883'
down_revision = 'e488a1f408e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ble_beacons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_table('beacon_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('beacon_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beacon_id'], ['ble_beacons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beacon_id', 'department_id', name='uq_beacon_dept')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beacon_assignments')
    op.drop_table('ble_beacons')
    # ### end Alembic commands ###
