"""add standard_shift

Revision ID: 354dd35651e6
Revises: d13d99531a5a
Create Date: 2026-06-29 08:32:59.326568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354dd35651e6'
down_revision = 'd13d99531a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_work_date'), ['work_date'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_shift', sa.String(), server_default='morning', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('standard_shift')

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_work_date'))

    # ### end Alembic commands ###
