"""add_composite_index_attendance

Revision ID: 7b786ee992b7
Revises: eb458f2c9958
Create Date: 2026-06-17 16:29:53.922601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b786ee992b7'
down_revision = 'eb458f2c9958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('idx_emp_work_date', ['employee_id', 'work_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index('idx_emp_work_date')

    # ### end Alembic commands ###
