"""add parent_department_id to departments

Revision ID: a7c7e2dcb002
Revises: 354dd35651e6
Create Date: 2026-07-02 17:53:52.147280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c7e2dcb002'
down_revision = '354dd35651e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_dept_parent', 'departments', ['parent_department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dept_parent', type_='foreignkey')
        batch_op.drop_column('parent_department_id')

    # ### end Alembic commands ###
