"""align_db_schema

Revision ID: b23108964fdf
Revises: 7b786ee992b7
Create Date: 2026-06-17 10:06:45.947386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23108964fdf'
down_revision = '7b786ee992b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('record_changed', sa.UUID(), nullable=False),
    sa.Column('previous_clock_in', sa.DateTime(), nullable=True),
    sa.Column('previous_clock_out', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('reason_for_change', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_changed'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('job_title_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_manager', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_foreign_key(None, 'job_titles', ['job_title_id'], ['id'])

    op.alter_column('modules', 'name', new_column_name='module')
    op.drop_constraint('modules_name_key', 'modules', type_='unique')
    op.create_unique_constraint('modules_module_key', 'modules', ['module'])

    op.alter_column('roles', 'name', new_column_name='role')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint('roles_role_key', 'roles', ['role'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'role', new_column_name='name')
    op.drop_constraint('roles_role_key', 'roles', type_='unique')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])

    op.alter_column('modules', 'module', new_column_name='name')
    op.drop_constraint('modules_module_key', 'modules', type_='unique')
    op.create_unique_constraint('modules_name_key', 'modules', ['name'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_manager')
        batch_op.drop_column('job_title_id')
        batch_op.drop_column('password_hash')

    op.drop_table('audit_log')
    op.drop_table('job_titles')
    # ### end Alembic commands ###
