"""Turn departments into a general org tree.

Adds `unit_type` and `display_name`, scopes name uniqueness to the parent, and
makes the parent/employee foreign keys SET NULL on delete.

Revision ID: f1a3c7b92e04
Revises: d4b2c9e15f70
Create Date: 2026-07-20

Notes for anyone re-running this:

* `migrations/env.py` replays every revision once per tenant schema, under a
  `search_path` set to that schema. All statements here are therefore
  unqualified, and index names collide across schemas only in the sense that
  each schema gets its own — which is what we want.

* Nothing here can fail on existing data. `unit_type` arrives with a server
  default, `display_name` is nullable, and the new uniqueness rule is strictly
  *weaker* than the global one it replaces, so every current row already
  satisfies it.

* Constraints are dropped by raw SQL with IF EXISTS rather than
  `op.drop_constraint`. Tenant schemas were provisioned by two different paths
  (`flask db upgrade` and `seed_org.py`'s `create_all()`), so the autogenerated
  constraint name is not guaranteed identical everywhere.
"""

from alembic import op
import sqlalchemy as sa


revision = 'f1a3c7b92e04'
down_revision = 'd4b2c9e15f70'
branch_labels = None
depends_on = None


UNIT_TYPES = ('root', 'region', 'site', 'division', 'department', 'team')


def upgrade() -> None:
    # --- new columns -------------------------------------------------------
    op.add_column(
        'departments',
        sa.Column(
            'unit_type',
            sa.String(length=20),
            nullable=False,
            server_default='department',
        ),
    )
    op.add_column(
        'departments',
        sa.Column('display_name', sa.String(length=120), nullable=True),
    )
    op.create_check_constraint(
        'ck_dept_unit_type',
        'departments',
        "unit_type IN ('root','region','site','division','department','team')",
    )

    # --- name uniqueness: global -> scoped to the parent -------------------
    # Two partial indexes, not one composite. Postgres treats NULLs as distinct,
    # so UNIQUE(parent_department_id, name) would leave roots unconstrained.
    op.execute('ALTER TABLE departments DROP CONSTRAINT IF EXISTS departments_name_key')
    op.execute('DROP INDEX IF EXISTS departments_name_key')
    op.create_index(
        'uq_dept_parent_name',
        'departments',
        ['parent_department_id', 'name'],
        unique=True,
        postgresql_where=sa.text('parent_department_id IS NOT NULL'),
    )
    op.create_index(
        'uq_dept_root_name',
        'departments',
        ['name'],
        unique=True,
        postgresql_where=sa.text('parent_department_id IS NULL'),
    )

    # --- foreign keys: add ON DELETE SET NULL ------------------------------
    # Deleting a unit should orphan its children and staff, not cascade an entire
    # campus away and not hard-error. The routes still refuse such a delete
    # unless the caller supplies a reparent target; this is the backstop.
    op.execute('ALTER TABLE departments DROP CONSTRAINT IF EXISTS fk_dept_parent')
    op.create_foreign_key(
        'fk_dept_parent',
        'departments',
        'departments',
        ['parent_department_id'],
        ['id'],
        ondelete='SET NULL',
    )

    op.execute('ALTER TABLE employees DROP CONSTRAINT IF EXISTS employees_department_id_fkey')
    op.create_foreign_key(
        'employees_department_id_fkey',
        'employees',
        'departments',
        ['department_id'],
        ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    op.execute('ALTER TABLE employees DROP CONSTRAINT IF EXISTS employees_department_id_fkey')
    op.create_foreign_key(
        'employees_department_id_fkey',
        'employees',
        'departments',
        ['department_id'],
        ['id'],
    )

    op.execute('ALTER TABLE departments DROP CONSTRAINT IF EXISTS fk_dept_parent')
    op.create_foreign_key(
        'fk_dept_parent',
        'departments',
        'departments',
        ['parent_department_id'],
        ['id'],
    )

    op.drop_index('uq_dept_root_name', table_name='departments')
    op.drop_index('uq_dept_parent_name', table_name='departments')
    # Restoring the global unique constraint can fail if sibling units were given
    # colliding names while it was relaxed. That is inherent to going backwards,
    # not a bug here — deduplicate first if it happens.
    op.create_unique_constraint('departments_name_key', 'departments', ['name'])

    op.drop_constraint('ck_dept_unit_type', 'departments', type_='check')
    op.drop_column('departments', 'display_name')
    op.drop_column('departments', 'unit_type')
