import { defineConfig } from 'orval';

/**
 * Client generation from the TallyCheck service contracts.
 *
 * Input is the **bundled** spec under dist/api-spec, not the source file:
 * `docs/api/*.openapi.yaml` uses local $refs into `shared/`, and bundling
 * resolves those into one document. Run via `nx run api-client:generate`, which
 * depends on `bundle-spec`.
 *
 * Output is committed. That is deliberate — a generated diff appearing in a pull
 * request is the most effective contract-drift alarm available, and contributors
 * get types without running a generator.
 */
export default defineConfig({
  tcheck: {
    input: {
      target: '../../dist/api-spec/tcheck-corporate.yaml',
    },
    output: {
      mode: 'tags-split',
      target: './src/generated/tcheck/index.ts',
      schemas: './src/generated/tcheck/model',
      client: 'angular',
      clean: true,
      // Bake the base URL into the generated URL templates as a runtime call.
      // A constant will not do — dev, prod and demo builds target different
      // hosts — and it cannot be an InjectionToken, because the expression is
      // evaluated inside a service method, outside any injection context.
      baseUrl: {
        runtime: 'tcheckApiBase()',
        // orval resolves importPath relative to the output *directory* and adds
        // one level for the per-tag folder, so this yields
        // '../../../../base-url' -> libs/api-client/src/base-url from
        // src/generated/tcheck/<tag>/<tag>.service.ts.
        imports: [
          { name: 'tcheckApiBase', importPath: '../../base-url', values: true },
        ],
      },
      override: {
        header: (info) => [
          `Generated by orval from ${info.title} v${info.version}.`,
          'DO NOT EDIT — run `nx run api-client:generate` instead.',
          '',
        ],
      },
    },
    hooks: {
      // Keep generated output formatted the same way as hand-written code, so a
      // formatting change never shows up as a spurious contract diff.
      afterAllFilesWrite: 'prettier --write',
    },
  },
});
